[mongodb]
mongodb.daws84s.online
[catalogue]
catalogue.daws84s.online
[redis]
redis.daws84s.online
[user]
user.daws84s.online
[cart]
cart.daws84s.online
[frontend]
frontend.daws84s.online
[mysql]
mysql.daws84s.online
[shipping]
shipping.daws84s.online
[rabbitmq]
rabbitmq.daws84s.online
[payment]
payment.daws84s.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321